# Build the Go Binary.
FROM golang:1.13 as build_books-api
ENV CGO_ENABLED 0
ARG VCS_REF
ARG PACKAGE_NAME
ARG PACKAGE_PREFIX

# Create a location in the container for the source code. Using the
# default GOPATH location.
RUN mkdir -p /book-library

# Copy the module files first and then download the dependencies. If this
# doesn't change, we won't need to do this again in future builds.
COPY go.* /book-library/
WORKDIR /book-library
RUN go mod download

# Copy the source code into the container.
COPY private.pem private.pem
COPY cmd cmd
COPY internal internal

# Build the admin tool so we can have it in the container. This should change
# often so do this first.
WORKDIR /book-library/cmd/${PACKAGE_PREFIX}admin
RUN go build -ldflags "-X main.build=${VCS_REF}"

# Build the service binary. We are doing this last since this will be different
# every time we run through this process.
WORKDIR /book-library/cmd/${PACKAGE_PREFIX}${PACKAGE_NAME}
RUN go build -ldflags "-X main.build=${VCS_REF}"


# Run the Go Binary in Alpine.
FROM alpine:3.7
ARG BUILD_DATE
ARG VCS_REF
ARG PACKAGE_NAME
ARG PACKAGE_PREFIX
COPY --from=build_books-api /book-library/private.pem /app-library/private.pem
COPY --from=build_books-api /book-library/cmd/${PACKAGE_PREFIX}admin/admin /app-library/book-api
COPY --from=build_books-api /book-library/cmd/${PACKAGE_PREFIX}${PACKAGE_NAME}/${PACKAGE_NAME} /app-library/book-api
WORKDIR /app-library
CMD ["./book-api"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="book-api" \
      org.opencontainers.image.authors="Hergy Tchuinkou <tchuinkoufongue@gmail.com>" \
      org.opencontainers.image.source="https://github.com/rjtch/book-library/cmd/book-api" \
      org.opencontainers.image.revision="${VCS_REF}"