version: '3'

networks:
  shared-network:
    driver: bridge

services:

  # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  # This sidecar publishes metrics to the console by default.
  metrics:
    container_name: metrics
    networks:
      - shared-network
    image: ${PROJECT}/metrics
    ports:
      - 3001:3001 # EXPVAR API
      - 4001:4001 # DEBUG API

  #This is the core CRUD based service.
  books-api:
    container_name: books-api
    networks:
      - shared-network
    image: ${PROJECT}/books-api
    ports:
      - 3000:3000 # CRUD API
      - 4000:4000 # DEBUG API
    environment:
      - BOOKS_DB_HOST=book_db
      - BOOKS_DB_DISABLE_TLS=1 # This is only disabled for our development enviroment.
      # - GODEBUG=gctrace=1
    depends_on:
      - metrics
      - zipkin
      - db

  # This starts a local PostgreSQL DB.
  db:
    container_name: book_db
    networks:
      - shared-network
    image: postgres:11.1-alpine
    ports:
      - 5432:5432