# Build the Go Binary.
FROM golang:1.13 as build_metrics
ENV CGO_ENABLED 0
ARG VCS_REF
ARG PACKAGE_NAME
ARG PACKAGE_PREFIX

# Create a location in the container for the source code. Using the
# default GOPATH location.
RUN mkdir -p /book-library

# Copy the module files first and then download the dependencies. If this
# doesn't change, we won't need to do this again in future builds.
COPY go.* /book-library/
WORKDIR /book-library
RUN go mod download

# Copy the source code into the container.
WORKDIR /book-library
COPY . .

# Build the service binary. We are doing this last since this will be different
# every time we run through this process.
WORKDIR /book-library/cmd/sidebar/metrics
RUN go build -ldflags "-X main.build=${VCS_REF}"


# Run the Go Binary in Alpine.
FROM alpine:3.7
ARG BUILD_DATE
ARG VCS_REF
ARG PACKAGE_NAME
ARG PACKAGE_PREFIX
COPY --from=build_metrics /book-library/cmd/sidebar/metrics /app-library/main
WORKDIR /app-library
CMD /app-library/main