apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sales-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      name: books-api
      labels:
        service: books-api
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:2.11
          ports:
            - name: zipkin
              containerPort: 9411
          resources: {}
        - name: books-api
          image: hergytchuinkou/book-library:books-api
          env:
            - name: SALES_DB_HOST
              value: {{PRIVATE_DB_IP}}
          ports:
            - name: books-api
              containerPort: 3000
            - name: debug
              containerPort: 4000
          resources: {}
        - name: metrics
          image: hergytchuinkou/book-library:metrics
          env:
            - name: METRICS_COLLECT_FROM
              value: "http://localhost:4000/debug/vars"
          ports:
            - name: metrics
              containerPort: 3001
            - name: debug
              containerPort: 4001
          resources: {}
status: {}