/**
 * Book Library
 * This is a sample API that describes the structure of our Book-Library-Server 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserMessage { 
    category: UserMessage.CategoryEnum;
    code: string;
    path?: string;
    text?: string;
}
export namespace UserMessage {
    export type CategoryEnum = 'ERROR' | 'WARNING' | 'INFO';
    export const CategoryEnum = {
        Error: 'ERROR' as CategoryEnum,
        Warning: 'WARNING' as CategoryEnum,
        Info: 'INFO' as CategoryEnum
    };
}


