name: publish to registry
on:
  pull_request:
    branches:
      - develop

jobs:
  - uses: mr-smithers-excellent/docker-build-push@v4.0
  - name: Docker login
    run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
  - name: Build
    run: make all
  - name: Tags
    run: |
     docker tag book-library-kit ${{ secrets.DOCKERHUB_USERNAME }}/book-library-kit:${{ github.sha }}
     docker tag book-library-kit ${{ secrets.DOCKERHUB_USERNAME }}/book-library-kit:latest
  - name: Push
    run: |
     docker push ${{ secrets.DOCKERHUB_USERNAME }}/book-library-kit:${{ github.sha }}
     docker push ${{ secrets.DOCKER_USERNAME }}/book-library-kit:latest