name: publish to registry
on:
  push:
    branches:
      - develop

env:
  PROJECT: book-library
  DOCKERIMAGE-BOOK-API: hergytchuinkou/book-api-kit
  DOCKERIMAGE-METRICS: hergytchuinkou/book-metrics-kit
  REGISTRY_DOMAIN: openshift-registry.adorsys.de

  APPNAME: book-library

jobs:
  publish-book-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run build
        run: make books-api
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        run: make books-api
      - name: Tags
        run: |
          docker tag book-api-kit ${{ secrets.DOCKERHUB_USERNAME }}/book-api-kit:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/book-api-kit:latest

  publish-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run build
        run: make metrics
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        run: make metrics
      - name: Tags
        run: |
          docker tag book-metrics-kit ${{ secrets.DOCKERHUB_USERNAME }}/book-metrics-kit:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/book-metrics-kit:latest


  openshift-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: OpenShift Action
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: 'latest'
          openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL}}
          parameters: '{"username": "${{ secrets.USERNAME }}", "password": "${{ secrets.PASSWORD }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            oc project ${PROJECT}

            oc import-image  --confirm hergytchuinkou/book-api-kit:latest
            oc import-image  --confirm hergytchuinkou/book-metrics-kit:latest
            oc new-app --allow-missing-images openzipkin/zipkin:2.11
            oc new-app --allow-missing-images postgres:11.1-alpine
#            oc new-app --allow-missing-images docker-registry.default.svc:5000/book-library/book-api-kit
#            oc new-app --confirm --allow-missing-images docker-registry.default.svc:5000/book-library/book-metrics-kit