name: publish to registry
on:
  push:
    branches:
      - develop

env:
  PROJECT: book-library
  DOCKERIMAGE: hergytchuinkou/book-library-kit
  APPNAME: adorsys.book-library

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        run: make all
      - name: Tags
        run: |
          docker tag book-library-kit ${{ secrets.DOCKERHUB_USERNAME }}/book-library-kit:${{ github.sha }}
          docker tag book-library-kit ${{ secrets.DOCKERHUB_USERNAME }}/book-library-kit:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/book-library-kit:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/book-library-kit:latest

  openshift-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: OpenShift Action
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: 'latest'
          openshift_server_url: 'openshift-registry.adorsys.de'
          parameters: '{"apitoken": "${{ secrets.api.token }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            oc project ${PROJECT}
            oc new-build --strategy docker --binary --docker-image ${DOCKERIMAGE} --name ${APPNAME}
            oc start-build ${APPNAME} --from-dir . --follow
            oc new-app ${PROJECT}/${APPNAME}:latest
            oc expose svc/"${APPNAME}"