name: test and build

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.13.0'

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Run build
      run:  make build
            make keys