name: test and build

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.0'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Run build
        run:  make all

      - name: Generate keys
        run:  make keys

    #    - name: Run Tests
    #     run: make test
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        run: docker build -t back .
      - name: Tags
        run: |
          docker tag back ${{ secrets.DOCKERHUB_USERNAME }}/back:${{ github.sha }}
          docker tag back ${{ secrets.DOCKERHUB_USERNAME }}/back:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/back:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/back:latest